---
# nfs_server_configuration/tasks/Debian_configure_services_for_kerberos.yml

#
# Note:
# restarting nfs-server systemd unit is enough this also restarts:
# - rpc-svcgssd.service
# - nfs-mountd.service
# - nfs-idmapd.service

- name: 'Enable idmapd in /etc/default/nfs-common (needed for kerberized NFSv4)'
  ansible.builtin.lineinfile:
    path: '/etc/default/nfs-common'
    regex: '^NEED_IDMAPD'
    line: 'NEED_IDMAPD=yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart nfs-server'

- name: 'Enable gssd in /etc/default/nfs-common (needed for kerberized NFSv4)'
  ansible.builtin.lineinfile:
    path: '/etc/default/nfs-common'
    regex: '^NEED_GSSD'
    line: 'NEED_GSSD=yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart nfs-server'

- name: 'Enable svc.gssd in /etc/default/nfs-kernel-server (needed for kerberized NFSv4)'
  ansible.builtin.lineinfile:
    path: '/etc/default/nfs-kernel-server'
    regex: '^NEED_SVCGSSD'
    line: 'NEED_SVCGSSD="yes"'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart nfs-server'

- name: 'Disable rpc.gssd debugging output in /etc/default/nfs-kernel-server'
  ansible.builtin.lineinfile:
    path: '/etc/default/nfs-kernel-server'
    regex: '^RPCSVCGSSDOPTS'
    line: 'RPCSVCGSSDOPTS=""'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'not kerberos_rpcgssd_debugging | bool'
  notify:
    - 'Restart nfs-server'

- name: 'Enable rpc.gssd debugging output in /etc/default/nfs-kernel-server'
  ansible.builtin.lineinfile:
    path: '/etc/default/nfs-kernel-server'
    regex: '^RPCSVCGSSDOPTS'
    line: 'RPCSVCGSSDOPTS="-vvv"'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'kerberos_rpcgssd_debugging | bool'
  notify:
    - 'Restart nfs-server'
