---
# nfs_server_configuration/tasks/main.yml

- ansible.builtin.include_tasks: create_directories.yml
  when: 'nfs_server_exports is defined'

- ansible.builtin.include_tasks:
    file: Debian_configure_services_for_kerberos.yml
  when:
    - 'ansible_os_family == "Debian"'
    - 'enable_kerberos | bool'

- ansible.builtin.include_tasks: configure_exports_and_start_nfs_server.yml
  when: 'nfs_server_exports is defined'
